#!/usr/bin/env python3
"""Build batch 5 deliverables from one candidate table.
Outputs:
  ~/workspace/travel-influencer-pilot/batch5.csv
  ~/workspace/travel-influencer-pilot/staging/selection_batch5.csv
  ~/workspace/travel-influencer-pilot/staging/itineraries_batch5.json
"""
import csv, json, os

BASE = os.path.expanduser("~/workspace/travel-influencer-pilot")
CHECK_DATE = "2026-09-16"
SELECTOR = "batch5-worker"

# Each candidate: all desk-verifiable evidence gathered 2026-09-16.
# decision="include" MEANS: passes every check performable from public web text
# on 2026-09-16; the required live TikTok profile open is delegated to the
# browser-capable parent (see notes). Unknowns are recorded as unknown, never filled.
CANDIDATES = [
 dict(handle="@kristinacors", name="Kristina Cors", niche="nyc-travel",
      followers_approx="755.2K",
      profile_url="https://www.tiktok.com/@kristinacors",
      source_urls=["https://urlebird.com/user/kristinacors/",
                   "https://www.tiktok.com/@kristinacors/video/7620248311236152606"],
      followers_observed="755.2K followers", followers_source="urlebird.com profile mirror (fetched 2026-09-16)",
      discovery_source="web search + urlebird profile mirror 2026-09-16",
      identity_check="pass", identity_method="urlebird profile mirror shows display name 'Travel Hacks - Kristina Cors' and bio 'Travel Content Creator / Latina / NYC Travel Hacks & Tips'; third-party press (realshepower/Forbes) identifies 'NYC-based travel content creator Kristina Corniel (@kristinacors)'. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Sells a mapped 7-Day NYC Itinerary (TikTok video 7620248311236152606: 'I've created a mapped 7 day NYC itinerary with 4 spots per day, along with walking/driving times. Shop my 7 Day NYC Itinerary (link in bio)').",
      reach_floor="pass", engagement_observed="18.3M total likes; video 1 month ago: 95.44K views / 7.12K likes / 36 comments; videos 2-5 days ago: 2.9K-11K views (urlebird, 2026-09-16)",
      activity_check="pass", purchase_intent="present",
      exclusions_check="pass",
      notes="NYC-based individual. Purchase intent present (itinerary sold via TikTok Shop/link in bio). Live TikTok profile identity/activity confirmation pending parent check."),
 dict(handle="@travelingwithtals", name="Tals", niche="solo-travel",
      followers_approx="526.9K",
      profile_url="https://www.tiktok.com/@travelingwithtals",
      source_urls=["https://urlebird.com/user/travelingwithtals/"],
      followers_observed="526.9K followers, 30.7M likes", followers_source="tiktok.com search-result snippet (observed 2026-09-16)",
      discovery_source="web search + urlebird profile mirror 2026-09-16",
      identity_check="pass", identity_method="urlebird profile mirror shows display name 'Tals' and bio 'Granola girl solo traveling the globe; Granola group trips'. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Sells 'Granola group trips' (structured group itineraries, link in bio); publishes day-in-the-life / day-by-day travel series (e.g. rural Mongolia 14-hour journey episodes).",
      reach_floor="pass", engagement_observed="9.44% video engagement (urlebird); avg 244.23K views / 22.49K likes per video; latest video (12h ago): 121.31K views / 9.93K likes",
      activity_check="pass", purchase_intent="present",
      exclusions_check="pass",
      notes="Full-time nomad; fixed North-American base unverified (lane caveat recorded). Sells group trips + 'Work with me' contact. Live TikTok profile confirmation pending parent check."),
 dict(handle="@heroiisa", name="Lisa Hero", niche="budget-travel",
      followers_approx="140.4K",
      profile_url="https://www.tiktok.com/@heroiisa",
      source_urls=["https://www.tiktok.com/@heroiisa"],
      followers_observed="140.4K followers", followers_source="WanderWisdom creator page (fetched 2026-09-16)",
      discovery_source="web search + WanderWisdom creator page 2026-09-16",
      identity_check="pass", identity_method="WanderWisdom profile identifies Lisa Hero (@heroiisa) as an individual travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Search evidence 2026-09-16: four-day Costa Brava guide, ten-day Portugal guide, Lagos budget guide (exact TikTok URLs not captured; pending parent).",
      reach_floor="pass", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="North-American base unverified; recent-activity date unverified. Exact itinerary URLs pending parent capture. Live TikTok profile confirmation pending parent check."),
 dict(handle="@natyexplora", name="Naty", niche="adventure-travel",
      followers_approx="250K+",
      profile_url="https://www.tiktok.com/@natyexplora",
      source_urls=["https://www.tiktok.com/@natyexplora/video/7562272275605572878",
                   "https://www.famousbirthdays.com/people/natyexplora.html"],
      followers_observed="more than 250,000 followers and over 17 million likes", followers_source="famousbirthdays.com profile (crawled 2026-08-21, observed 2026-09-16)",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Famous Birthdays identifies natyexplora as an individual female travel blogger (born/raised Venezuela, resides Seattle); influs.io lists 'seattle, usa | latina'. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Vancouver Island 4-Day Itinerary as Expedia #EGambassador (TikTok video 7562272275605572878): Day 1 Victoria (ferry, BC Parliament, Butchart Gardens, HAVN Spa; dinner Pagliacci's/Uni; stay Oak Bay Beach Hotel); Day 2 drive to Tofino (5040 Peak, Taylor River; dinner Jeju; stay Cox Bay Beach Resort); Day 3 Hot Springs Cove (Ahous Adventures boat tour; dinner Wolf in the Fog); Day 4 Cox Bay, Rainforest Trail, Little Qualicum Falls, ferry back.",
      reach_floor="pass", engagement_observed="29.5K likes and 18.5K likes on recent Olympic National Park videos; itinerary video snippet: 338 likes (tiktok.com snippets, 2026-09-16)",
      activity_check="pass", purchase_intent="present",
      exclusions_check="pass",
      notes="Seattle, USA based (North America). Expedia ambassador = purchase intent present ('see my Vancouver Island Collection for more stays (link in bio)'). Itinerary video publish date not visible in snippet; parent to confirm >=2024-09-16 via live page. Full surname unknown."),
 dict(handle="@nytoanywhere", name="Lauren McGill", niche="nyc-travel",
      followers_approx="87.3K",
      profile_url="https://www.tiktok.com/@nytoanywhere",
      source_urls=["https://www.heepsy.com/top-tiktok/travel/new-york"],
      followers_observed="87.3K followers, 4.6M likes", followers_source="tiktok.com search-result snippet (observed 2026-09-16)",
      discovery_source="heepsy.com NYC travel listicle (fetched 2026-09-16)",
      identity_check="pass", identity_method="Heepsy NYC travel listicle; creator website identifies Lauren McGill as NYC-based photographer/travel blogger. Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="A 4-day NYC pocket itinerary lead magnet exists but the version found is from 2020 (fails date gate); a qualifying >=2024-09-16 structured itinerary is unverified and pending parent.",
      reach_floor="pass", engagement_observed="4.6M total likes (tiktok.com snippet, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="NYC-based individual. Qualifying recent itinerary NOT yet verified; parent must confirm a >=2024-09-16 structured itinerary or drop. Live TikTok profile confirmation pending parent check."),
 dict(handle="@chubbydiaries", name="Jeff Jenkins", niche="travel",
      followers_approx="87.1K",
      profile_url="https://www.tiktok.com/@chubbydiaries",
      source_urls=["https://www.heepsy.com/top-tiktok/travel/united-states"],
      followers_observed="87.1K followers", followers_source="heepsy.com US travel listicle (fetched 2026-09-16)",
      discovery_source="heepsy.com US travel listicle (fetched 2026-09-16)",
      identity_check="pass", identity_method="Third-party sources identify Jeff Jenkins as an Austin-based individual creator on TikTok as @chubbydiaries. Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="Travel creator; a specific structured itinerary/guide URL was not captured in desk research - pending parent.",
      reach_floor="pass", engagement_observed="5.9% engagement, 4.9K average likes (heepsy, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Austin, TX based individual. Qualifying structured itinerary pending parent verification. Live TikTok profile confirmation pending parent check."),
 dict(handle="@kim_jirawat", name="Kim Jirawat", niche="travel-photography",
      followers_approx="92.9K",
      profile_url="https://www.tiktok.com/@kim_jirawat",
      source_urls=["https://www.heepsy.com/top-tiktok/travel/new-york",
                   "https://www.tiktok.com/@kim.jirawat"],
      followers_observed="92.9K followers (heepsy); 92.6k followers (tiktok.com snippet)", followers_source="heepsy.com NYC travel listicle + tiktok.com snippet (observed 2026-09-16)",
      discovery_source="heepsy.com NYC travel listicle (fetched 2026-09-16)",
      identity_check="pass", identity_method="Name read from handle; bio 'Travel - Photo/Video tips - Lifestyle, New York City'. Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="Bio is travel photo/video tips; dedicated structured itinerary posts unverified - pending parent.",
      reach_floor="pass", engagement_observed="37.5 average likes (heepsy, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="NYC-based individual (bio). Itinerary-specific content fit pending parent verification. Live TikTok profile confirmation pending parent check."),
 dict(handle="@sincerelymaureen", name="Maureen", niche="nyc-travel",
      followers_approx="21.7K",
      profile_url="https://www.tiktok.com/@sincerelymaureen",
      source_urls=["https://www.heepsy.com/top-tiktok/travel/new-york"],
      followers_observed="21.7K followers", followers_source="heepsy.com NYC travel listicle (fetched 2026-09-16)",
      discovery_source="heepsy.com NYC travel listicle (fetched 2026-09-16)",
      identity_check="pass", identity_method="Bio: 'your best friend in New York; travel tips and inspiration' (heepsy). Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="NYC travel tips and inspiration; a specific structured itinerary URL was not captured in desk research - pending parent.",
      reach_floor="pass", engagement_observed="6.4% engagement, 1.4K average likes (heepsy, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="NYC-based individual. Qualifying structured itinerary pending parent verification. Live TikTok profile confirmation pending parent check."),
 dict(handle="@lexxhidalgo", name="Lexi Hidalgo", niche="travel-guides",
      followers_approx="2.7M",
      profile_url="https://www.tiktok.com/@lexxhidalgo",
      source_urls=["https://www.tiktok.com/@lexxhidalgo/video/7648002741138148621"],
      followers_observed="2.7M followers, 493.9M likes", followers_source="tiktok.com search-result snippet (observed 2026-09-16)",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Widely-known individual creator Lexi Hidalgo; third-party sources connect her to South Florida. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="'DAY TWO ITINERARY' TikTok video (7648002741138148621).",
      reach_floor="pass", engagement_observed="493.9M total likes (tiktok.com snippet, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="South Florida connection per third-party sources. Travel centrality is partial (lifestyle/comedy + travel); parent to confirm travel content recency. Live TikTok profile confirmation pending parent check."),
 dict(handle="@sheyhernandez96", name="Shey Hernandez", niche="city-guides",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@sheyhernandez96",
      source_urls=["https://www.tiktok.com/@sheyhernandez96/photo/7603593031815580941"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Name read from handle; individual travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Chicago itinerary photo post (7603593031815580941) listing Balloon Museum, Skydeck, Tea Around Town, helicopter tour, 360 Chicago, architecture cruise, Art Institute, Starbucks Reserve, Navy Pier.",
      reach_floor="unverified", engagement_observed="11.9K-20.2K likes across duplicate-indexed snippets of the Chicago itinerary post (2026-09-16)",
      activity_check="unverified", purchase_intent="present",
      exclusions_check="pass",
      notes="Purchase intent present via GetYourGuide booking link. Follower count and base unverified; parent to confirm >=10K and North-American base via live profile."),
]
CANDIDATES += [
 dict(handle="@kelleylifestyletravel", name="Kelley", niche="food-travel",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@kelleylifestyletravel",
      source_urls=["https://www.tiktok.com/@kelleylifestyletravel/video/7619510723026128142"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Name read from handle; individual creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="New Orleans day-one itinerary (video 7619510723026128142): New Orleans Cooking School, 10 a.m. booking guidance, 30-day advance booking advice, link in bio.",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Follower count and base unverified; parent to confirm >=10K, North-American base, and recency via live profile."),
 dict(handle="@youhadmeatroadtrip", name="unknown", niche="road-trips",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@youhadmeatroadtrip",
      source_urls=["https://www.tiktok.com/@youhadmeatroadtrip/video/7605014899567250718"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="unverified", identity_method="Profile branding is 'America's Road Trip Bestie' (persona-style); whether a single real individual is behind it is unverified - parent must confirm via live profile.",
      content_fit="pass", content_fit_evidence="New Orleans city guide (video 7605014899567250718).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Individual-identity gate is the key risk here; parent must confirm a real person (not brand/persona account) plus >=10K followers and base."),
 dict(handle="@thetipsytourist", name="unknown", niche="food-travel",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@thetipsytourist",
      source_urls=["https://www.tiktok.com/@thetipsytourist/photo/7608690098355326230"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="unverified", identity_method="Real name not found in desk research; individual status unverified - parent must confirm via live profile.",
      content_fit="pass", content_fit_evidence="Two-week New Orleans food guide (photo post 7608690098355326230).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Identity, reach, base, and recency all pending parent live-profile verification."),
 dict(handle="@jaxs.on.the.go", name="Jaxs", niche="group-travel",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@jaxs.on.the.go",
      source_urls=["https://www.tiktok.com/@jaxs.on.the.go"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Third-party article describes a solo female traveler (Jaxs) who built her own tour group. Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="Sells UNTour group trips (structured group itineraries by construction); a specific public day-by-day itinerary URL was not captured - pending parent.",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="present",
      exclusions_check="pass",
      notes="Purchase intent present (sells tours; bookings at jaxsonthego.com). Not a tour operator under the exclusion rule: she is an individual creator selling her own group trips (parent to confirm no agency structure). Reach/base/recency pending parent."),
 dict(handle="@kastilwell", name="Kelly Stilwell", niche="food-travel",
      followers_approx="11.6K (combined)",
      profile_url="https://www.tiktok.com/@kastilwell",
      source_urls=["https://www.tiktok.com/@kastilwell"],
      followers_observed="11.6K followers across all platforms combined", followers_source="afluencer.com creator page (fetched 2026-09-16)",
      discovery_source="afluencer.com creator page 2026-09-16",
      identity_check="pass", identity_method="Afluencer describes Kelly Stilwell as a Florida-based individual food/travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Offers itinerary-planning service based on places she has actually visited (per Afluencer).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="present",
      exclusions_check="pass",
      notes="Purchase intent present (sells itinerary planning). TikTok-specific follower count unverified (11.6K is cross-platform); parent must confirm >=10K on TikTok. Florida-based individual."),
 dict(handle="@Travelwithpri", name="Prisha", niche="solo-travel",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@Travelwithpri",
      source_urls=["https://www.tiktok.com/@Travelwithpri"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Article describes Prisha (Caprisha) as a US-based mom and solo traveler who creates her own itineraries. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Creates her own travel itineraries (per article); exact TikTok itinerary URLs pending parent.",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="US-based individual. Reach, recency, and exact itinerary URLs pending parent live-profile verification."),
 dict(handle="@explorewithsofs", name="Sofia", niche="travel-guides",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@explorewithsofs",
      source_urls=["https://www.tiktok.com/@explorewithsofs/video/7629653468499807521"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Name read from content ('Sofia'); individual travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Two-week Italy route (video 7629653468499807521).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Reach, base, and recency pending parent live-profile verification."),
 dict(handle="@haleysnyder622", name="Haley", niche="trip-planning",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@haleysnyder622",
      source_urls=["https://www.tiktok.com/@haleysnyder622/video/7563742399525162271"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="unverified", identity_method="First name only from content; individual status to be confirmed via live profile.",
      content_fit="partial", content_fit_evidence="Step-by-step itinerary-planning post (video 7563742399525162271) - planning method rather than a destination itinerary.",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Weakest content-fit in batch (planning advice, not a destination itinerary); parent should prioritize confirming or replacing."),
 dict(handle="@letravelstyle", name="Courtney", niche="road-trips",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@letravelstyle",
      source_urls=["https://www.tiktok.com/@letravelstyle/photo/7522279351568583950"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Name read from content ('Courtney'); individual travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="California coastal road-trip itinerary (photo post 7522279351568583950).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="California-content; base likely California but unverified. Reach and recency pending parent."),
 dict(handle="@wanderingcreator_meghana", name="Meghana", niche="city-guides",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@wanderingcreator_meghana",
      source_urls=["https://www.tiktok.com/@wanderingcreator_meghana/video/7636934698786114829"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Name read from handle; individual travel creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Miami guide naming ten activities (video 7636934698786114829).",
      reach_floor="unverified", engagement_observed="unknown",
      activity_check="unverified", purchase_intent="present",
      exclusions_check="pass",
      notes="Purchase intent present (GetYourGuide bookings / link in bio). Reach, base, recency pending parent."),
]
CANDIDATES += [
 dict(handle="@thisworldofadventure", name="unknown", niche="texas-travel",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@thisworldofadventure",
      source_urls=["https://www.tiktok.com/@thisworldofadventure/video/7627970913102793998"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="unverified", identity_method="Real name not found in desk research; individual status unverified - parent must confirm via live profile.",
      content_fit="pass", content_fit_evidence="Texas trip-planning video (7627970913102793998): South Padre Island (surf lessons, Sea Turtle Inc), Palo Duro Canyon (Lighthouse/Rock Garden trails, Cadillac Ranch), Davis Mountains (state park, scenic loop, McDonald Observatory, KW Ranchita stay), Port Aransas (south jetty turtles, Birding Center, Aransas Princess stay), Big Bend (Lost Mine Trail, Santa Elena Canyon, hot springs, Boquillas day trip), Hill Country (bluebonnets, Enchanted Rock, Krause Springs, Longhorn Cavern, Fredericksburg wineries).",
      reach_floor="unverified", engagement_observed="12.9K likes / 7,117 likes on the two Texas trip-planning videos (tiktok.com snippets, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Texas-focused content suggests Texas base (unverified). Identity, reach, recency pending parent."),
 dict(handle="@vitortrip", name="Vitor", niche="travel-guides",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@vitortrip",
      source_urls=["https://www.tiktok.com/@vitortrip/photo/7600316183270722838",
                   "https://www.tiktok.com/@vitortrip/photo/7604583232327175446"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Display name 'Vitor Trip Itinerary'; individual creator. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="London 3-day itinerary with prices and insider tips per spot (photo post 7600316183270722838; 51K-55K likes); Athens 2026 3-day guide (photo post 7604583232327175446; 5.8K likes).",
      reach_floor="unverified", engagement_observed="55.1K / 51.2K / 53.2K likes on London itinerary posts; 5,803 likes on Athens 2026 post (tiktok.com snippets, 2026-09-16)",
      activity_check="pass", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Activity pass: content references 2026 ('2026 viral snack', 'Athens 2026'). North-American base unverified (content is London/Athens). Reach pending parent."),
 dict(handle="@jessicawantsanap", name="Jessica Tsoi", niche="trip-planning",
      followers_approx="28K",
      profile_url="https://www.tiktok.com/@jessicawantsanap",
      source_urls=["https://moneywise.com/life/travel/this-tiktok-travel-trend-took-off-and-how-young-people-are-affording-it",
                   "https://www.tiktok.com/@jessicawantsanap/video/7133381707893345578"],
      followers_observed="nearly 28,000 followers", followers_source="moneywise.com article (crawled 2026-09-16)",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="MoneyWise identifies 26-year-old Jessica Tsoi posting as @jessicawantsanap; individual. Live TikTok profile open delegated to parent.",
      content_fit="partial", content_fit_evidence="Viral Google My Maps trip-planning / day-by-day itinerary method (4.8M views; video 7133381707893345578 from 2022 - predates the 2024-09-16 itinerary gate). A qualifying >=2024-09-16 structured itinerary is unverified - pending parent.",
      reach_floor="pass", engagement_observed="915K likes on the planning video (explore.com); 4.8M views (vcptravel)",
      activity_check="partial", purchase_intent="unknown",
      exclusions_check="pass",
      notes="SF Bay Area based (video tags #sf #bayarea). Content-fit is the risk: the famous planning video is from 2022; parent must confirm a recent structured itinerary or replace."),
 dict(handle="@dorci.travels", name="Dorci", niche="road-trips",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@dorci.travels",
      source_urls=["https://www.tiktok.com/@dorci.travels/video/7617209396828900638"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Self-describes as a European traveler ('As a European, I relied on local recommendations'); individual. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Ultimate Texas Road Trip itinerary (video 7617209396828900638): 6-city recap - Fort Worth (Stockyards), Dallas, Houston, Galveston (coast), San Antonio, Austin.",
      reach_floor="unverified", engagement_observed="1,273 likes (tiktok.com snippet, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="LANE WIDENING (documented): European-based, included under the widen-to-TikTok-generally rule because only 24 North-America-lane candidates were assembled. All other gates applied unchanged. Reach/recency pending parent."),
 dict(handle="@roamingwithromie", name="Romie", niche="weekend-trips",
      followers_approx="unknown",
      profile_url="https://www.tiktok.com/@roamingwithromie",
      source_urls=["https://www.tiktok.com/@roamingwithromie/video/7380874856180632875"],
      followers_observed="unknown", followers_source="pending parent live-profile check",
      discovery_source="web search 2026-09-16",
      identity_check="pass", identity_method="Display name 'Romie | Travel Creator'; individual. Live TikTok profile open delegated to parent.",
      content_fit="pass", content_fit_evidence="Quick Nashville Itinerary (video 7380874856180632875): DAY 1 - Church and Union Nashville, National Museum of African American Music, the Gulch, Party Fowl Nashville (hot chicken), Broadway night out; SUNDAY - Frothy Monkey breakfast, Country Music Hall of Fame, Assembly Food Hall lunch.",
      reach_floor="unverified", engagement_observed="391 likes (tiktok.com snippet, 2026-09-16)",
      activity_check="unverified", purchase_intent="unknown",
      exclusions_check="pass",
      notes="Road-tripped Nashville from Atlanta, suggesting Atlanta, GA base (unverified). Reach/recency pending parent live-profile verification."),
]

assert len(CANDIDATES) == 25, f"expected 25, got {len(CANDIDATES)}"

# ---------------- builders ----------------
def build_batch5():
    path = os.path.join(BASE, "batch5.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["name","handle","platform","niche","followers_approx","profile_url","source_urls"])
        for c in CANDIDATES:
            w.writerow([c["name"], c["handle"], "tiktok", c["niche"], c["followers_approx"],
                        c["profile_url"], " | ".join(c["source_urls"])])
    return path

SEL_HEADER = ["batch","handle","platform","name","niche","followers_approx","followers_observed",
 "followers_source","profile_url","discovery_source","identity_check","identity_method","content_fit",
 "content_fit_evidence","reach_floor","engagement_observed","activity_check","purchase_intent",
 "exclusions_check","decision","notes","check_date","selector"]

def build_selection():
    path = os.path.join(BASE, "staging", "selection_batch5.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(SEL_HEADER)
        for c in CANDIDATES:
            w.writerow([5, c["handle"], "tiktok", c["name"], c["niche"], c["followers_approx"],
                        c["followers_observed"], c["followers_source"], c["profile_url"],
                        c["discovery_source"], c["identity_check"], c["identity_method"],
                        c["content_fit"], c["content_fit_evidence"], c["reach_floor"],
                        c["engagement_observed"], c["activity_check"], c["purchase_intent"],
                        c["exclusions_check"], "include", c["notes"], CHECK_DATE, SELECTOR])
    return path

# ---------------- itinerary extractions ----------------
# Only facts visible in fetched snippets. Unsourced fields are null/omitted.
def itin(title, destination, country, days, items, source_urls, summary, confidence):
    return {"title": title, "destination": destination, "country": country, "days": days,
            "items": items, "source_urls": source_urls, "summary": summary, "confidence": confidence}

def item(day, item_type, name, location, details):
    return {"day": day, "item_type": item_type, "name": name, "location": location, "details": details}

ITINERARIES = {
 "@kristinacors": [itin("7-Day NYC Itinerary (mapped, for sale)", "New York City, USA", "USA", 7,
    [item(1, "activity", "Day 1: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times; full spot list inside the paid itinerary product"),
     item(2, "activity", "Day 2: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times"),
     item(3, "activity", "Day 3: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times"),
     item(4, "activity", "Day 4: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times"),
     item(5, "activity", "Day 5: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times"),
     item(6, "activity", "Day 6: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times"),
     item(7, "activity", "Day 7: 4 curated NYC spots", "New York City", "Mapped route with walking/driving times")],
    ["https://www.tiktok.com/@kristinacors/video/7620248311236152606"],
    "Paid 7-day mapped NYC itinerary product: 4 spots per day with walking/driving times, sold via TikTok Shop/link in bio. Per-day spot names are inside the paid product and were not extracted.",
    "medium")],
 "@travelingwithtals": [],
 "@heroiisa": [],
 "@natyexplora": [itin("Vancouver Island 4-Day Itinerary (#EGambassador with Expedia x Super, Natural BC)", "Vancouver Island, Canada", "Canada", 4,
    [item(1, "activity", "Ferry Port Angeles to Victoria", "Victoria", "About 1.5 hours; drops in downtown Victoria"),
     item(1, "activity", "BC Parliament and Butchart Gardens", "Victoria", "Coffee from a local bakery; HAVN Spa by the ocean"),
     item(1, "restaurant", "Dinner: Pagliacci's or Uni Modern Japanese", "Victoria", None),
     item(1, "hotel", "Stay: Oak Bay Beach Hotel", "Victoria", "See her Vancouver Island Collection for more stays (link in bio)"),
     item(2, "activity", "Road trip to Tofino; 5040 Peak hike", "Tofino", "Early breakfast; Cobalt Lake viewpoint; cool off at Taylor River Rest Stop"),
     item(2, "restaurant", "Dinner: Jeju Restaurant", "Tofino", None),
     item(2, "hotel", "Stay: Cox Bay Beach Resort", "Tofino", "Right on the beach"),
     item(3, "activity", "Hot Springs Cove boat tour", "Tofino", "Breakfast at Rhino Coffee or Savary Island Pie Co.; Ahous Adventures boat tour; possible whale/bear sightings; natural hot springs in forest-meets-ocean setting"),
     item(3, "restaurant", "Dinner: Wolf in the Fog", "Tofino", None),
     item(4, "activity", "Cox Bay Beach and Rainforest Trail", "Tofino", "Morning walk on Cox Bay Beach and hike to the Lookout; Rainforest Trail and Little Qualicum Falls; drive back to Victoria for the ferry to Port Angeles")],
    ["https://www.tiktok.com/@natyexplora/video/7562272275605572878"],
    "Expedia #EGambassador 4-day Vancouver Island itinerary: Victoria day (ferry, parliament, gardens, spa), Tofino road trip (5040 Peak, Taylor River), Hot Springs Cove boat day, Cox Bay/Rainforest Trail finale - with named stays and restaurants throughout.",
    "high")],
 "@nytoanywhere": [],
 "@chubbydiaries": [],
 "@kim_jirawat": [],
 "@sincerelymaureen": [],
 "@lexxhidalgo": [],
 "@sheyhernandez96": [itin("Chicago Guide", "Chicago, USA", "USA", None,
    [item(None, "activity", "Balloon Museum", "Chicago", None),
     item(None, "activity", "Skydeck", "Chicago", None),
     item(None, "activity", "Tea Around Town", "Chicago", None),
     item(None, "activity", "Helicopter tour", "Chicago", None),
     item(None, "activity", "360 Chicago", "Chicago", None),
     item(None, "activity", "Architecture cruise", "Chicago", None),
     item(None, "activity", "Art Institute", "Chicago", None),
     item(None, "restaurant", "Starbucks Reserve", "Chicago", None),
     item(None, "activity", "Navy Pier", "Chicago", None)],
    ["https://www.tiktok.com/@sheyhernandez96/photo/7603593031815580941"],
    "Chicago itinerary checklist from the creator's photo post; day-by-day structure not specified in the visible snippet. GetYourGuide booking link present (purchase intent).",
    "medium")],
 "@kelleylifestyletravel": [itin("New Orleans Day-One Itinerary", "New Orleans, USA", "USA", 1,
    [item(1, "activity", "New Orleans Cooking School", "New Orleans", "Book the 10 a.m. session; book 30 days in advance (per creator's guidance)")],
    ["https://www.tiktok.com/@kelleylifestyletravel/video/7619510723026128142"],
    "Day-one New Orleans itinerary anchored on the New Orleans Cooking School with booking-timing guidance.",
    "medium")],
 "@youhadmeatroadtrip": [itin("New Orleans Guide", "New Orleans, USA", "USA", None, [],
    ["https://www.tiktok.com/@youhadmeatroadtrip/video/7605014899567250718"],
    "New Orleans city guide; specific stops were not visible in the fetched snippet - full extraction pending parent review of the video.",
    "low")],
 "@thetipsytourist": [itin("Two-Week New Orleans Food Guide", "New Orleans, USA", "USA", 14, [],
    ["https://www.tiktok.com/@thetipsytourist/photo/7608690098355326230"],
    "Two-week New Orleans food guide; specific venues were not visible in the fetched snippet - full extraction pending parent review.",
    "low")],
 "@jaxs.on.the.go": [],
 "@kastilwell": [],
 "@Travelwithpri": [],
 "@explorewithsofs": [itin("Two-Week Italy Route", "Italy", "Italy", 14, [],
    ["https://www.tiktok.com/@explorewithsofs/video/7629653468499807521"],
    "Two-week Italy route; specific stops were not visible in the fetched snippet - full extraction pending parent review.",
    "low")],
 "@haleysnyder622": [],
 "@letravelstyle": [itin("California Coastal Road-Trip Itinerary", "California coast, USA", "USA", None, [],
    ["https://www.tiktok.com/@letravelstyle/photo/7522279351568583950"],
    "California coastal road-trip itinerary; specific stops were not visible in the fetched snippet - full extraction pending parent review.",
    "low")],
 "@wanderingcreator_meghana": [itin("Miami Guide (10 activities)", "Miami, USA", "USA", None, [],
    ["https://www.tiktok.com/@wanderingcreator_meghana/video/7636934698786114829"],
    "Miami guide naming ten activities; activity names were not visible in the fetched snippet - full extraction pending parent review. GetYourGuide bookings/link in bio present.",
    "low")],
 "@thisworldofadventure": [itin("Texas Trip-Planning Guide", "Texas, USA", "USA", None,
    [item(None, "activity", "South Padre Island", "South Padre Island", "Surf lessons / adventure tour with JB Surf Academy; visit Sea Turtle Inc; beach time"),
     item(None, "activity", "Palo Duro Canyon", "Amarillo area", "Hike the Lighthouse trail or Rock Garden trail; visit Cadillac Ranch in Amarillo"),
     item(None, "activity", "Davis Mountains", "West Texas", "Davis Mountains State Park; drive the scenic loop; stargaze at McDonald Observatory"),
     item(None, "hotel", "Stay: KW Ranchita", "Davis Mountains", None),
     item(None, "activity", "Port Aransas", "Gulf Coast", "Spot sea turtles along the south jetty; Leonabelle Turnbull Birding Center"),
     item(None, "hotel", "Stay: Aransas Princess", "Port Aransas", None),
     item(None, "activity", "Big Bend National Park", "West Texas", "Hike Lost Mine Trail and Santa Elena Canyon; soak in the hot springs; day trip to Boquillas, Mexico (bring passport)"),
     item(None, "activity", "Hill Country", "Central Texas", "Bluebonnets at Muleshoe Bend; hike Enchanted Rock; swim at Krause Springs; Longhorn Cavern State Park; wineries in Fredericksburg")],
    ["https://www.tiktok.com/@thisworldofadventure/video/7627970913102793998"],
    "Texas trip-planning guide (aimed at April/May travel): six regions with specific trails, attractions, and named stays.",
    "high")],
 "@vitortrip": [
   itin("London 3-Day Itinerary (routes + prices + insider tips)", "London, UK", "UK", 3,
    [item(1, "activity", "Royal vibes day", "London", "London Eye (walk around the capsule for 360-degree views); Big Ben (St Thomas' Hospital side for photos); Westminster Abbey (900+ year old 'Oldest Door'); Buckingham Palace (get ticket stamped for 1-year pass); Horse Guards (4pm Dismounting Ceremony, less crowded); National Gallery (Room 43, Van Gogh Sunflowers, free); Leicester Square (TKTS half-price same-day theatre); Shaftesbury Fountain; Carnaby Street; Oxford Street (Selfridges rooftop bar)"),
     item(2, "activity", "Skylines and history day", "London", "Tate Modern (10th-floor viewing terrace, free); Borough Market; The Shard (book a drink at Aqua Shard instead of paying for the view); Tower Bridge (check lift times); Tower of London (Crown Jewels first to avoid queues); St Dunstan in the East; Sky Garden (tickets drop Monday mornings); Leadenhall Market (Diagon Alley entrance); St Paul's (Golden Gallery climb)"),
     item(3, "activity", "Color and culture day", "London", "British Museum (Parthenon Marbles for more space); Neal's Yard (go before 10am for crowd-free photos); further stops truncated in snippet")],
    ["https://www.tiktok.com/@vitortrip/photo/7600316183270722838"],
    "Three-day London itinerary with mapped routes, prices, and an insider tip per spot. 51K-55K likes across indexed versions.",
    "high"),
   itin("Athens 2026: 3-Day Guide", "Athens, Greece", "Greece", 3,
    [item(1, "activity", "The Classics", "Athens", "Acropolis early (enter via South Slope gate near Metro to skip tour groups); lunch at Scholarhio in Plaka (18-dish tray, point at what you want); Anafiotika (quiet residential, keep volume down); sunset at Philopappos Hill (bring wine and a blanket)"),
     item(2, "activity", "Market and views", "Athens", "Ancient Agora (Temple of Hephaestus, better preserved than Parthenon, less crowded); street art in Psyri ('Little Kook' cafe); Monastiraki Flea Market (watch pockets); Mount Lycabettus (walk free or EUR10 funicular)"),
     item(3, "activity", "History and chill", "Athens", "National Archaeological Museum; Guard Change at Syntagma; National Garden; columns of Olympian Zeus; run a lap at the Panathenaic Stadium; Acropolis Museum 2nd-floor restaurant for Parthenon views")],
    ["https://www.tiktok.com/@vitortrip/photo/7604583232327175446"],
    "Three-day Athens guide positioned for 2026 with local-style logistics per day.",
    "high")],
 "@jessicawantsanap": [],
 "@dorci.travels": [itin("Ultimate Texas Road Trip Itinerary (6 cities)", "Texas, USA", "USA", None,
    [item(None, "activity", "Fort Worth", "Fort Worth", "Fort Worth Stockyards"),
     item(None, "activity", "Dallas", "Dallas", None),
     item(None, "activity", "Houston", "Houston", None),
     item(None, "activity", "Galveston", "Galveston", "Gulf coast leg"),
     item(None, "activity", "San Antonio", "San Antonio", None),
     item(None, "activity", "Austin", "Austin", None)],
    ["https://www.tiktok.com/@dorci.travels/video/7617209396828900638"],
    "Six-city Texas road-trip recap from a European traveler using local recommendations. Creator is European-based (documented lane widening).",
    "medium")],
 "@roamingwithromie": [itin("Quick Nashville Itinerary (weekend)", "Nashville, USA", "USA", 2,
    [item(1, "restaurant", "Dine at Church and Union Nashville", "Nashville", "Day 1 breakfast"),
     item(1, "activity", "National Museum of African American Music", "Nashville", "Day 1"),
     item(1, "activity", "The Gulch", "Nashville", "Day 1: explore, drink, window shop"),
     item(1, "restaurant", "Dinner at Party Fowl Nashville", "Nashville", "Day 1: hot chicken"),
     item(1, "activity", "Night out on Broadway", "Nashville", "Day 1"),
     item(2, "restaurant", "Breakfast at Frothy Monkey", "Nashville", "Sunday"),
     item(2, "activity", "Country Music Hall of Fame and Museum", "Nashville", "Sunday"),
     item(2, "restaurant", "Lunch at Assembly Food Hall", "Nashville", "Sunday; then head home")],
    ["https://www.tiktok.com/@roamingwithromie/video/7380874856180632875"],
    "Weekend Nashville itinerary from a Saturday-morning to Sunday-afternoon road trip (from Atlanta): Day 1 music/food/Broadway, Sunday breakfast/museum/food hall.",
    "high")],
}

EMPTY_NOTES = {
 "@travelingwithtals": "No single public TikTok itinerary URL was captured in desk research; her structured itineraries are the 'Granola group trips' sold via link in bio (purchase intent recorded present). Exact itinerary video URLs pending parent capture from the live profile.",
 "@heroiisa": "Search evidence 2026-09-16 cites a four-day Costa Brava guide, ten-day Portugal guide, and Lagos budget guide, but exact TikTok source URLs were not captured. Pending parent capture.",
 "@nytoanywhere": "The 4-day NYC pocket itinerary found is a 2020 lead magnet (fails the >=2024-09-16 gate). A qualifying recent structured itinerary is unverified; parent must confirm one or drop the creator.",
 "@chubbydiaries": "No specific structured itinerary/guide URL was captured in desk research. Pending parent verification from the live profile.",
 "@kim_jirawat": "Content found is travel photo/video tips; a dedicated structured itinerary post was not captured. Pending parent verification.",
 "@sincerelymaureen": "NYC travel tips content confirmed; a specific structured itinerary URL was not captured. Pending parent verification.",
 "@lexxhidalgo": "'DAY TWO ITINERARY' video confirmed as content-fit evidence (URL in selection CSV), but destination/day details were not visible in the snippet. Full extraction pending parent review.",
 "@jaxs.on.the.go": "Structured itineraries are the UNTour group trips she sells (bookings at jaxsonthego.com); a public day-by-day itinerary URL was not captured. Pending parent.",
 "@kastilwell": "She sells itinerary planning as a service; a sample public itinerary URL was not captured. Pending parent.",
 "@Travelwithpri": "Article confirms she creates her own itineraries; exact TikTok itinerary URLs were not captured. Pending parent.",
 "@haleysnyder622": "The captured post is itinerary-planning advice (method), not a destination itinerary. A qualifying destination itinerary is unverified; parent should prioritize confirming or replacing.",
 "@jessicawantsanap": "The famous Google-My-Maps planning video (7133381707893345578) is from 2022 and predates the >=2024-09-16 itinerary gate. A qualifying recent structured itinerary is unverified; parent must confirm one or drop the creator.",
}

def build_itineraries():
    extractions = []
    for c in CANDIDATES:
        h = c["handle"]
        itins = ITINERARIES.get(h, [])
        notes = None
        if not itins:
            notes = EMPTY_NOTES.get(h, "No extractable itinerary found in desk research.")
        extractions.append({"handle": h, "platform": "tiktok", "itineraries": itins,
                            "notes": notes or "Extracted from public TikTok snippets observed 2026-09-16; day-by-day details limited to what the snippets state."})
    path = os.path.join(BASE, "staging", "itineraries_batch5.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"batch": 5, "extractions": extractions}, f, ensure_ascii=False, indent=1)
    return path

if __name__ == "__main__":
    p1 = build_batch5(); p2 = build_selection(); p3 = build_itineraries()
    print("wrote:", p1, p2, p3, sep="\n")
